### ISSUE TITLE
Zasada DRY

### ISSUE THREAD

**Issue by grzanka** [Kudyyy/Logika#2]
Zeby nie lamac zasady DRY, to proponuje wykorzystac taka sztuczke:

```
>>> e = "(lambda x:x)(2)"
>>> print(e, eval(e))
(lambda x:x)(2) 2
```

**Comment by Kudyyy** [comment]
Dziekuje ponownie za zwrocenie uwagi, mysle ze dokonalem wystarczajacych zmian w kodzie i mozna zamknac issue.
